config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  workdir: ~/.config/dotdrop
  default_actions:
  - loginstall "/tmp/dotdrop-installation.log"
actions:
  loginstall: echo {{@@ _dotfile_abs_src @@}} installed to {{@@ _dotfile_abs_dst @@}}
    >> {0}
  install_fisher: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
  install_tpm: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm &&
    echo "Installed Tmux Plugin Manager"
  install_libtmux: pip install --user libtmux && echo "Installed libtmux"
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    chmod: '644'
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_lattedockrc:
    src: config/lattedockrc
    dst: ~/.config/lattedockrc
    chmod: '600'
  f_nate-custom.layout.latte:
    src: config/latte/nate-custom.layout.latte
    dst: ~/.config/latte/nate-custom.layout.latte
    chmod: '644'
  f_kwinrc:
    src: config/kwinrc
    dst: ~/.config/kwinrc
    chmod: '600'
  f_breezerc:
    src: config/breezerc
    dst: ~/.config/breezerc
    chmod: '600'
  f_kglobalshortcutsrc:
    src: config/kglobalshortcutsrc
    dst: ~/.config/kglobalshortcutsrc
    chmod: '600'
  f_dolphinrc:
    src: config/dolphinrc
    dst: ~/.config/dolphinrc
    chmod: '600'
  f_kdeglobals:
    src: config/kdeglobals
    dst: ~/.config/kdeglobals
    chmod: '600'
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  f_gtkrc:
    src: config/gtkrc
    dst: ~/.config/gtkrc
  f_gtkrc-2.0:
    src: config/gtkrc-2.0
    dst: ~/.config/gtkrc-2.0
  f_ksplashrc:
    src: config/ksplashrc
    dst: ~/.config/ksplashrc
    chmod: '600'
  f_plasmarc:
    src: config/plasmarc
    dst: ~/.config/plasmarc
    chmod: '600'
  f_trolltech.conf:
    src: config/Trolltech.conf
    dst: ~/.config/Trolltech.conf
  f_yakuakerc:
    src: config/yakuakerc
    dst: ~/.config/yakuakerc
    chmod: '600'
  f_kcminputrc:
    src: config/kcminputrc
    dst: ~/.config/kcminputrc
    chmod: '600'
  f_kxkbrc:
    src: config/kxkbrc
    dst: ~/.config/kxkbrc
    chmod: '600'
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_hn-tui.toml:
    src: config/hn-tui.toml
    dst: ~/.config/hn-tui.toml
  f_nate-custom-v3.layout.latte:
    src: config/latte/nate-custom-v3.layout.latte
    dst: ~/.config/latte/nate-custom-v3.layout.latte
    chmod: '644'
  f_config.yml:
    src: config/wtf/config.yml
    dst: ~/.config/wtf/config.yml
    chmod: '600'
  f_copy-path.desktop:
    src: local/share/kservices5/copy-path.desktop
    dst: ~/.local/share/kservices5/copy-path.desktop
    chmod: '644'
  d_doom.d:
    src: doom.d
    dst: ~/.doom.d
  f_eslintrc.json:
    src: eslintrc.json
    dst: ~/.eslintrc.json
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
  f_lazygit_config.yml:
    src: config/lazygit/config.yml
    dst: ~/.config/lazygit/config.yml
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_tmux-modal.conf:
    src: tmux-modal.conf
    dst: ~/.tmux-modal.conf
  f_tmux-powerlinerc:
    src: tmux-powerlinerc
    dst: ~/.tmux-powerlinerc
  f_custom.sh:
    src: tmux/plugins/tmux-powerline/themes/custom.sh
    dst: ~/.tmux/powerline-custom/themes/custom.sh
  d_powerline-custom:
    src: tmux/powerline-custom
    dst: ~/.tmux/powerline-custom
  f_init.el:
    src: config/emacs/init.el
    dst: ~/.config/emacs/init.el
  f_early-init.el:
    src: config/emacs/early-init.el
    dst: ~/.config/emacs/early-init.el
  d_plugins:
    src: config/BetterDiscord/plugins
    dst: ~/.config/BetterDiscord/plugins
  d_themes:
    src: config/BetterDiscord/themes
    dst: ~/.config/BetterDiscord/themes
  f_config.toml:
    src: config/helix/config.toml
    dst: ~/.config/helix/config.toml
  d_helix:
    src: config/helix
    dst: ~/.config/helix
profiles:
  neovim:
    dotfiles:
    - d_nvim
  zsh:
    dotfiles:
    - f_zshrc
    - f_p10k.zsh
  kitty:
    dotfiles:
    - d_kitty
  kde:
    dotfiles:
    - f_kwinrc
    - f_breezerc
    - f_kglobalshortcutsrc
    - f_dolphinrc
    - f_kdeglobals
    - d_gtk-3.0
    - f_gtkrc
    - f_gtkrc-2.0
    - f_ksplashrc
    - f_plasmarc
    - f_trolltech.conf
    - f_yakuakerc
    - f_kcminputrc
    - f_kxkbrc
    - f_copy-path.desktop
  nate-H81M-DS2:
    dotfiles:
    - d_config_nvim
  hackernews-tui:
    dotfiles:
    - f_hn-tui.toml
  latte-dock:
    dotfiles:
    - f_nate-custom.layout.latte
    - f_nate-custom-v3.layout.latte
  wtfutil:
    dotfiles:
    - f_config.yml
  doom-emacs:
    dotfiles:
    - d_doom.d
  eslint:
    dotfiles:
    - f_eslintrc.json
  fish:
    dotfiles:
    - d_fish
    actions:
    - install_fisher
  lazygit:
    dotfiles:
    - f_lazygit_config.yml
  tmux:
    dotfiles:
    - f_tmux.conf
    - f_tmux-modal.conf
    - f_tmux-powerlinerc
    - d_powerline-custom
    actions:
    - install_tpm
    - install_libtmux
  emacs:
    dotfiles:
    - f_init.el
    - f_early-init.el
  betterdiscord:
    dotfiles:
    - d_plugins
    - d_themes
  helix:
    dotfiles:
    - f_config.toml
    - d_helix
